{
 "title": "Node1",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "Frequency",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_frequency_current{job=\"logging\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "cpu_frequency_max{job=\"logging\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "cpu_frequency_min{job=\"logging\"}",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "CPU count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_count{job=\"logging\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Percent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_percent{job=\"logging\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "network_io_bytes_recv{job=\"logging\"}",
     "legendFormat": "recv"
    },
    {
     "expr": "network_io_bytes_sent{job=\"logging\"}",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "free_disk_space{job=\"logging\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "total_disk_space{job=\"logging\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Disk read/write",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_io_read_count{job=\"logging\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "disk_io_write_count{job=\"logging\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "SSH active sessions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ssh_active_count{job=\"logging\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSH logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "cacheDurationSeconds": 300,
     "fields": [
      { "jsonPath": "$.logs[*]" }
     ],
     "method": "GET",
     "urlPath": "/metrics_auth"
    }
   ]
  }
 ]
}