version : '3.3'

services:
  grafana:
    image: grafana/grafana:9.5.12
#    build:
#      context: .
#      dockerfile: Dockerfile.grafana
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    networks:
      static:
        ipv4_address: 172.16.1.4

  prometheus:
    image: prom/prometheus:v2.30.3
    container_name: prometheus
    ports:
      - 9000:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    networks:
      static:
        ipv4_address: 172.16.1.3

  logger1:
    build:
      context: .
      dockerfile: Dockerfile.logger
    container_name: logger1
    ports:
      - 8080:8080
    restart: unless-stopped
    volumes:
      - ./app:/app
    networks:
      static:
        ipv4_address: 172.16.1.2


volumes:
  grafana-data:
  prometheus-data:

networks:
  static:
    ipam:
      config:
        - subnet: 172.16.1.0/24
